/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Indicates whether the transaction is a credit or a debit entry.
 */
@JsonAdapter(OBCreditDebitCode1.Adapter.class)
public enum OBCreditDebitCode1 {
  CREDIT("Credit"),
  DEBIT("Debit");

  private String value;

  OBCreditDebitCode1(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OBCreditDebitCode1 fromValue(String text) {
    for (OBCreditDebitCode1 b : OBCreditDebitCode1.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OBCreditDebitCode1> {
    @Override
    public void write(final JsonWriter jsonWriter, final OBCreditDebitCode1 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OBCreditDebitCode1 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OBCreditDebitCode1.fromValue(String.valueOf(value));
    }
  }
}
