/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of interest rate, Fixed or Variable
 */
@JsonAdapter(OBInterestFixedVariableType1Code.Adapter.class)
public enum OBInterestFixedVariableType1Code {
  INFI("INFI"),
  INVA("INVA");

  private String value;

  OBInterestFixedVariableType1Code(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OBInterestFixedVariableType1Code fromValue(String text) {
    for (OBInterestFixedVariableType1Code b : OBInterestFixedVariableType1Code.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OBInterestFixedVariableType1Code> {
    @Override
    public void write(final JsonWriter jsonWriter, final OBInterestFixedVariableType1Code enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OBInterestFixedVariableType1Code read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OBInterestFixedVariableType1Code.fromValue(String.valueOf(value));
    }
  }
}
